CREATE TABLE `aircraft` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `year` int(11) NOT NULL,
 `manufacturer` varchar(255) NOT NULL,
 `model` varchar(255) NOT NULL,
 `aircraftCondition` varchar(10) NOT NULL,
 `serialNumber` varchar(100) NOT NULL,
 `totalTime` float NOT NULL,
 `totalLandings` int(11) NOT NULL,
 `engineType` varchar(50) NOT NULL,
 `engineHours` int(11) NOT NULL,
 `engineCycles` int(11) NOT NULL,
 `adsbEquipped` int(11) NOT NULL,
 `avionics` text NOT NULL,
 `colorScheme` varchar(255) NOT NULL,
 `galley` int(11) NOT NULL,
 `galleyConfig` varchar(255) NOT NULL,
 `lavatory` int(11) NOT NULL,
 `lavatoryConfig` varchar(255) NOT NULL,
 `interior` text NOT NULL,
 `inspection` varchar(255) NOT NULL,
 `numberSeats` int(11) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
